/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute, setDefaultHandler } from 'workbox-routing'
import { NetworkFirst, NetworkOnly } from 'workbox-strategies'

declare const self: ServiceWorkerGlobalScope

// let the new SW claim clients immediately after activation
clientsClaim()

// inject the precache manifest generated by workbox at build time
precacheAndRoute(self.__WB_MANIFEST)

// skip API requests — let them go straight to the network
registerRoute(
  ({ url }) => url.origin !== self.location.origin,
  new NetworkOnly()
)

// serve same-origin JS/CSS assets from network first, falling back to cache
registerRoute(
  ({ request, url }) =>
    url.origin === self.location.origin &&
    (request.destination === 'script' || request.destination === 'style'),
  new NetworkFirst()
)

// navigation requests (HTML pages) — network first with cache fallback
registerRoute(({ request }) => request.mode === 'navigate', new NetworkFirst())

// default handler for anything else from the same origin
setDefaultHandler(new NetworkFirst())

// skip waiting only when the client explicitly requests it
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// push notification support
self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {}
  const title = data.title || 'Sharlushka'
  const options = {
    body: data.body || '',
    icon: '/img/sh-og-img.webp',
    badge: '/img/sh-og-img.webp',
    data: data.url ? { url: data.url } : undefined
  }
  console.log('[SW] push received:', data)

  event.waitUntil(self.registration.showNotification(title, options))
})

// open the app when the user taps a notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const url = event.notification.data?.url || '/'
  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // focus an existing tab if one is open
        for (const client of windowClients) {
          if (client.url === url && 'focus' in client) {
            return client.focus()
          }
        }
        return self.clients.openWindow(url)
      })
  )
})
